import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, FileText } from 'lucide-react';
import { API_URL } from '../api';
const TERMS = [
  {
    title: 'Authorised Use',
    text: 'This portal is provided to SDMCET faculty and administrators for preparing, formatting and generating syllabus documents. Access is granted only after administrator approval, and the portal must be used only for official academic purposes.',
  },
  {
    title: 'Account Responsibility',
    text: 'You are responsible for keeping your login credentials confidential and must not share your account with anyone. All activity carried out through your account is your responsibility. Report any suspected unauthorised access to the administrator immediately.',
  },
  {
    title: 'Accuracy of Syllabus Content',
    text: 'Faculty are responsible for the accuracy and completeness of the details they enter, including course outcomes, unit content, contact hours, credits, textbooks and reference books. Please verify all content before it is submitted for review.',
  },
  {
    title: 'Outcome-Based Education (OBE) Compliance',
    text: 'Course Outcomes (COs) must be mapped to the Program Outcomes (POs) and Program Specific Outcomes (PSOs) using correlation levels of Substantial (3), Moderate (2) or Slight (1), and a hyphen (-) where there is no mapping. The total of the unit-wise teaching hours must match the prescribed contact hours.',
  },
  {
    title: 'References and Copyright',
    text: 'Textbooks and reference books must be cited in a consistent format giving author, title, edition, publisher and year. Do not enter material copied from other sources without proper acknowledgement or permission.',
  },
  {
    title: 'Review and Approval',
    text: 'Documents generated by this portal are drafts until they are reviewed and approved through the institution\'s prescribed academic procedure. Generating a document here does not by itself make it an official syllabus.',
  },
  {
    title: 'Data and Privacy',
    text: 'The portal stores your name, institutional email and the syllabus content you enter, only for the purpose of operating the portal. This information must not be shared outside the institution without proper authorisation.',
  },
  {
    title: 'Acceptable Use',
    text: 'Do not attempt to access other users\' accounts, bypass the approval process, disrupt the portal, or enter inappropriate or harmful content. The administrator may withdraw access from any user who violates these terms.',
  },
  {
    title: 'Changes to These Terms',
    text: 'These terms may be updated from time to time. Continued use of the portal means you accept the current terms.',
  },
];

export default function Terms() {
  const navigate = useNavigate();
  const [agreed, setAgreed] = useState(false);
  const [saving, setSaving] = useState(false);

const handleContinue = async () => {
  setSaving(true);
  try {
    const res = await fetch(`${API_URL}/auth/accept-terms`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${localStorage.getItem('token')}` },
    });
    if (!res.ok) throw new Error();
    const user = JSON.parse(localStorage.getItem('user') || '{}');
    localStorage.setItem('user', JSON.stringify({ ...user, termsAccepted: true }));
    navigate('/home');
  } catch {
    alert('Could not save your acceptance. Please try again.');
  } finally {
    setSaving(false);
  }
};

  return (
    <div className="min-h-screen bg-slate-100 flex items-center justify-center p-4">
      <div className="w-full max-w-2xl bg-white rounded-3xl p-8 border border-slate-200 shadow-xl">
        
        <div className="flex items-center gap-4 pb-6 border-b border-slate-100">
          <div className="w-12 h-12 rounded-2xl bg-orange-100 text-orange-600 flex items-center justify-center font-bold">
            <FileText className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-900">
              SDMCET Academic Terms & Conditions
            </h2>
            <p className="text-xs text-slate-500">
              Curriculum Authoring, OBE Verification & Institutional Guidelines
            </p>
          </div>
        </div>

        <div className="my-6 p-4 bg-slate-50 border border-slate-200 rounded-2xl text-xs text-slate-700 space-y-3 max-h-72 overflow-y-auto leading-relaxed">
        {TERMS.map((t, i) => (
  <div key={i}>
    <p className="font-semibold text-slate-900">{i + 1}. {t.title}</p>
    <p>{t.text}</p>
  </div>
))}  
        </div>

        {/* Checkbox */}
        <label className="flex items-start gap-3 cursor-pointer select-none mb-6">
          <input
            type="checkbox"
            checked={agreed}
            onChange={(e) => setAgreed(e.target.checked)}
            className="mt-0.5 w-4 h-4 rounded border-slate-300 text-orange-600 focus:ring-orange-500"
          />
          <span className="text-xs text-slate-700 font-medium">
            I have read and agree to the Terms and Conditions and abide by the SDMCET autonomous curriculum policies.
          </span>
        </label>

        {/* Continue Button (Disabled until checked) */}
        <button
          onClick={handleContinue}
          disabled={!agreed || saving}
          className={`w-full py-3 px-4 rounded-xl font-bold text-sm flex items-center justify-center gap-2 transition-all ${
            agreed
              ? 'bg-orange-600 hover:bg-orange-700 text-white shadow-lg shadow-orange-500/25 cursor-pointer'
              : 'bg-slate-200 text-slate-400 cursor-not-allowed'
          }`}
        >
          <span>Continue to Programme Selection</span>
          <ArrowRight className="w-4 h-4" />
        </button>

      </div>
    </div>
  );
}